# Generated by Django 5.0.1 on 2024-01-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asosiy_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='asosiy/')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kompyuterlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='kompyuterlarimiz/')),
                ('nomi', models.CharField()),
                ('ekran', models.CharField()),
                ('xotira', models.CharField()),
                ('operativ_xotira', models.CharField()),
                ('operatsion_sistema', models.CharField()),
                ('grafichiskiy', models.CharField()),
                ('narxi', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Noutbuklarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='noutbuklarimiz/')),
                ('nomi', models.CharField()),
                ('ekran', models.CharField()),
                ('xotira', models.CharField()),
                ('operativ_xotira', models.CharField()),
                ('operatsion_sistema', models.CharField()),
                ('grafichiskiy', models.CharField()),
                ('rangi', models.CharField()),
                ('narxi', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Oyin_kompyuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='oyin_uchun_komyuterlarimiz/')),
                ('nomi', models.CharField()),
                ('ekran', models.CharField()),
                ('xotira', models.CharField()),
                ('operativ_xotira', models.CharField()),
                ('grafichiskiy', models.CharField()),
                ('operatsion_sistema', models.CharField()),
                ('narxi', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='printerlarimiz/')),
                ('nomi', models.CharField()),
                ('olchami', models.CharField()),
                ('quvati', models.CharField()),
                ('rasm_nisbati', models.CharField()),
                ('narxi', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='telefonlarimiz')),
                ('nomi', models.CharField()),
                ('ekran', models.CharField()),
                ('xotira', models.CharField()),
                ('operativ_xotira', models.CharField()),
                ('narxi', models.CharField()),
            ],
        ),
    ]
